### ISSUE TITLE
carddav inconsistent

### ISSUE THREAD

**Issue by ScottPeterJohnson** [ScottPeterJohnson/purelymail-issues#102]
(This issue was imported from Gitea)
**ssemke** on March 16, 2022:
I'm testing carddav between Thunderbird (TB) and Roundcube (RC).

Here are some test results.  Don't know if the issue is TB, RC, or purely server.

1. No contact in TB or RC.  Create contact in TB.
1.1 Sync TB
1.2 Sync RC
Result good:
Contact in TB
Contact in RC

2. Contact exists in RC+TB.  Delete contact from TB.
2.1 Sync TB
2.2 Sync RC
Result bad:
Contact deleted from TB
Contact remains in RC

3. Create contact in RC.
3.1 Sync RC
3.2 Sync TB
Result bad:
Contact in RC
Contact not in TB

4. Contact exists in RC+TB.  Delete contact in RC
4.1 Sync RC
4.2 Sync TB
Result bad:
Contact deleted from RC
Contact remains in TB

**Comment by ScottPeterJohnson** [comment]
Comment by **ssemke** on March 16, 2022:
Sorry, I started by filing an issue.  I should have started by saying: 

Thank you, what a good email service.  Love the simplicity and ease of configuration.  You gladly have my $10.

Cheers

**Comment by ScottPeterJohnson** [comment]
Comment by **Scott** on March 18, 2022:
It seems like contact sync to Thunderbird isn't working, due to Thunderbird breaking a small part of the spec and Purelymail enforcing it. 

I've disabled the enforcement, so in about an hour or two when that code deploys, your test cases might actually work if you try them again.

**Comment by ssemke** [comment]
Confirmed as working.  Thank you!
