### ISSUE TITLE
Can't sign up - Australian phone number not accepted

### ISSUE THREAD

**Issue by andy47** [ScottPeterJohnson/purelymail-issues#106]
Hi, I'm trying to sign up but can't submit the sign up form because it is telling me that my Australian phone number is invalid.

I've selected Australia in the country drop down and the field shows a template value - in this case '0412 345 678'. But when I enter my mobile number in a similar format '0412 07x xxx' I get an error message saying 'Invalid phone number'.

Can you help me work out how best to enter my number to enable me to sign up. Thanks in advance.

**Comment by ScottPeterJohnson** [comment]
It seems the phone number code wasn't handling some international numbers like yours that well- I've updated it, so maybe it will work if you try again?
If not, feel free to email/Discord/whatever other means (does Github have private messages?) message me, and I can give you a signup code instead.

**Comment by andy47** [comment]
Works like a charm now. I'm all signed up. Thanks for the quick response.
