### ISSUE TITLE
Suggestion - Use Flarum for a community driven issues portal

### ISSUE THREAD

**Issue by ghost** [ScottPeterJohnson/purelymail-issues#107]
The guys from Kagi Search have a very well made issues portal (https://kagifeedback.org/) using https://flarum.org/ (free) and it's designed in a way that would be very interesting for Purelymail. One can open a bug/issue or a suggestion and there's a way to upvote, comment, answer, etc

**Comment by ScottPeterJohnson** [comment]
I might consider this later, but I'm happy with github issues for now (since it's well-known and I don't have to maintain anything).
