### ISSUE TITLE
Filter all not spam rule

### ISSUE THREAD

**Issue by justinkelly** [ScottPeterJohnson/purelymail-issues#109]
Hi PurelyMail,

Firstly thanks for the great service! really apreciated

Secondly, I'm trying to setup a filter rule in the webmail client that sends a copy of a message to a email address if the email is not spam

using header `x-spam-status` not contain `yes ,`

Question: 
1 - can filters work on spam headers?
2 - if they can, can you spot the error with my config (refer below)?

![image](https://user-images.githubusercontent.com/249520/162556967-92d74f8b-61aa-4415-acdb-fe78d518c566.png)

 When I use the again config, i get a boucebak style email with the error `The error encountered was: Command if (3:1): Test not (3:4): Test header (3:8): null`

**Comment by ScottPeterJohnson** [comment]
This seems like a bug- the X-Spam-Status header is available to Sieve scripts on requests, but is generated on-demand if not already present which seems to have a bug in it.
Also I might as well take the time to add a spamtest extension so you don't have to parse headers: https://datatracker.ietf.org/doc/html/rfc3685#section-2.2

**Comment by justinkelly** [comment]
Thanks Scott, greatly appreciate the update, looking forward to seeing the big fixed!

**Comment by ScottPeterJohnson** [comment]
The header bug should be fixed; should get to the spamtest extension eventually.

**Comment by justinkelly** [comment]
thanks @ScottPeterJohnson !! - i've tested this and my filter rule is now working

thank you

**Comment by ScottPeterJohnson** [comment]
You may have seen a few more sporadic SieveExceptions around timeouts; those should be fixed now too.
