### ISSUE TITLE
One of the emails have different date format

### ISSUE THREAD

**Issue by rEnr3n** [ScottPeterJohnson/purelymail-issues#114]
I downloaded my emails using isync. I tried to open my email client, himalaya. I get an error saying it cannot parse maildir message date. I checked the email and I saw this:

```
Received: from smtp-nlb02 ([10.141.249.58]) by M61SV059 with Microsoft SMTPSVC(10.0.17763.1);
	 Fri, 5 Feb 2021 22:05:02 +0800
Date: 05-FEB-2021 22:05:02
```

That's three lines. In other emails, it looked like `Date: Fri, 5 Feb 2021 22:05:02 +0800`

**Comment by ScottPeterJohnson** [comment]
You probably want to raise this as a bug in Himalaya:
https://github.com/soywod/himalaya

The SMTP RFCs say that your email should be in a certain format, but historically mail servers (including Purelymail) have grudgingly accepted and stored whatever you gave them, exactly as is. So you really do have a mail that was genuinely delivered with a wonky Date header somewhere, and your client should do a better job of handling such cases.
