### ISSUE TITLE
CardDAV Mobile Phone is mapped incorrectly

### ISSUE THREAD

**Issue by nabzord** [ScottPeterJohnson/purelymail-issues#130]
'Mobile' phone in the webapp is showing as 'Other' phone when synced via DAVx5

**Comment by nabzord** [comment]
Workaround, i can just mark mobile phone numbers as 'Pager'. Lol, of course pager would still work in this 10 year old vcard protocol. Nothing against purelymail though, I love this service so far. Great service.

**Comment by nabzord** [comment]
Boy I put my foot in my mouth, it might actually be how my native contact/dialer app on my GrapheneOS phone implements CardDAV. I have no clue though.

**Comment by ScottPeterJohnson** [comment]
I think Roundcube is basically labeling it as "mobile" when it should be "cell".
I opened an issue with the CardDAV plugin we use:
https://github.com/mstilkerich/rcmcarddav/issues/390

**Comment by ScottPeterJohnson** [comment]
This should be fixed now- big thanks to the RCMCardDav maintainer.

**Comment by nabzord** [comment]
cool, works now, thanks!

On 2022-10-07 09:00, Scott Johnson wrote:

> This should be fixed now- big thanks to the RCMCardDav maintainer.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/ScottPeterJohnson/purelymail-issues/issues/130#issuecomment-1271317930
[2]
