### ISSUE TITLE
Reserved address suggestion (website@purelymail.com)

### ISSUE THREAD

**Issue by michael-at-boost** [ScottPeterJohnson/purelymail-issues#133]
I went to reg website@mydomain and noticed that website@purelymail.com is available.
Could be worth adding to the reserved list, or maybe I just think that because my sites use that address.
Either way, keep up the good work mate

**Comment by ScottPeterJohnson** [comment]
Good suggestion! I've added it to the surprisingly long list of abusable shared names, which should be updated soon.
