### ISSUE TITLE
DKIM Subject signing

### ISSUE THREAD

**Issue by Leny1337** [ScottPeterJohnson/purelymail-issues#134]
Hello,
I'm using DKIM verify addon on Thunderbird and noticed, that `Subject` header is not signed.
https://help.returnpath.com/hc/en-us/articles/222438487-DKIM-signature-header-detail
looking at those details, it's just modifying `h` section:
```
h= is a list of headers that will be used in the signing algorithm to create the hash found in the b= tag. The order of the headers in the h= tag is the order in which they were presented during DKIM signing, and therefore is also the order in which they should be presented during verification. The value is a list of header fields that won’t change or be removed.
```

**Comment by ScottPeterJohnson** [comment]
Good catch! Not sure why Subject isn't in the list of headers to sign; hopefully it's just an oversight and I won't discover any bizarre reason I forgot.

**Comment by ScottPeterJohnson** [comment]
This was fixed a couple weeks ago but I forgot to update, sorry!
