### ISSUE TITLE
GBs of emails sent don't affect the price in the pricing calculator

### ISSUE THREAD

**Issue by Jackenmen** [ScottPeterJohnson/purelymail-issues#136]
Whatever I do, changing the field on the screenshot does not change the calculated price:
![image](https://user-images.githubusercontent.com/6032823/186983575-9dbdabe6-1d67-4113-a600-d99dd239c353.png)
Example:
![image](https://user-images.githubusercontent.com/6032823/186983600-f8d5a878-330d-4c6e-a9bd-339fc628332a.png)

**Comment by ScottPeterJohnson** [comment]
I couldn't replicate this in Chrome or Firefox. Maybe you had JS disabled?
Feel free to reopen with browser info if it keeps happening. And see if you can open the browser console (usually control+shift+K) and if it has any errors logger.
