### ISSUE TITLE
Addresses in simple routing are case sensitive 

### ISSUE THREAD

**Issue by rogerjane** [ScottPeterJohnson/purelymail-issues#141]
Kind of. It seems that the ‘exact match’ text has to be lower case to work. I’m guessing it’s compared to a lower cased version of the address in the email on receipt but in that case it should be lower cased itself before use. 

That seems to be the bug anyway…

Rog

**Comment by ScottPeterJohnson** [comment]
This should now be fixed- turns out they weren't being downcased when first created, only updated.
