### ISSUE TITLE
Search not filtering

### ISSUE THREAD

**Issue by nmasur** [ScottPeterJohnson/purelymail-issues#144]
Hi Scott,

I'm a recent Purelymail convert, happily using it. I've noticed that the search function doesn't appear to do anything, either in the webmail or in my client (Apple Mail).

Every time I search, every message is returned. For example, I have 827 messages in my inbox. I search for the word "iweoinadicoawekdsjf" and it returns 827 messages. No matter which client I use, or what I search for, I always get every message in the results.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/7386960/198417727-ec4bc2de-4b30-4e11-9c2b-466a44d093b5.png">

Not sure if this is a bug, or if there's something I'm doing wrong? Either way, thanks for your help!

**Comment by ScottPeterJohnson** [comment]
This is expected behavior for a user who has "Enable search indexing" disabled- the system can't efficiently perform some types of search, so it has to return all messages.
Can you check if you do?

**Comment by nmasur** [comment]
Whoops, good catch. Yes, that was the problem! I enabled the setting and after a few minutes, search is now working.

For those who see this in the future and don't know how to change it:

- Login to to the account admin portal
- Click Users and click on your user
- "Enable search indexing" is near the top

Thanks again!
