### ISSUE TITLE
Cannot add new domain in Firefox

### ISSUE THREAD

**Issue by aurabindo** [ScottPeterJohnson/purelymail-issues#148]
I tried adding a custom domain with my trial account, but it fails when I try in Firefox. Works on Chrome. Steps to repro:

* Sign up for a trial account
* Go  to domains, add the required records and verify them
* Click the checkbox below the "Save" button.

Observation on Firefox: A dotted line appears around the checkbox but its not selected, and is unable to click Save. Clicking save gives an error asking me to select the checkbox

System info:
Firefox: 107.0 (64-bit)
OS: Archlinux

**Comment by ScottPeterJohnson** [comment]
This happened intermittently and could often be solved by refreshing the page, but AFAIK should now be fixed.
