### ISSUE TITLE
Roundcube searches containing unicode characters fail

### ISSUE THREAD

**Issue by kotsius** [ScottPeterJohnson/purelymail-issues#150]
I find it impossible to search Roundcube folders for strings containing unicode (Greek in my case) characters. The result is always:

![sCapture-748](https://user-images.githubusercontent.com/35947133/206843957-106dfbd3-3a5f-44e5-bee8-f1bf78897455.png)

This would be a serious defect for users using languages other than English.

**Comment by ScottPeterJohnson** [comment]
Apparently this could happen if you searched with a "sort" on (instead of "None"). Should now be fixed.

**Comment by kotsius** [comment]
It seems to be working now, thank you!
