### ISSUE TITLE
Roundcube Identities Disappeared?

### ISSUE THREAD

**Issue by bai-yi-bai** [ScottPeterJohnson/purelymail-issues#151]
Hi,
I'm using a lot of routing and it t seems that all the identities I set up in Roundcube have disappeared. 

This is my general procedure:

1. Choose an email address to set up, log in to the administrator portal, navigate to the routing page, add the email and send it to my chosen user account, save changes.
2. Log in to my webmail (round cub), go to Settings>Folders, and add a new folder.
3. Go to Filters>Actions>Edit Filter Set and add the 'fileinto' rule.
4. Go to Identities Create and fill in the "Display Name", "Email", and "Reply-To" fields.

Again, all the identities I had set up previously were gone when I went to do this today.

I see either two possibilities:
a. My iOS mail app did something to my identities.
b. Something else ...? A Roundcube bug? A problem with an SQL query because I hadn't set up all the fields?

I dunno what's up... anyhow great service, please keep up the good work.

**Comment by ScottPeterJohnson** [comment]
As far as I know Roundcube stores its "Identities" in its own database, that other mail apps shouldn't be able to access. I can check what happened to them if you email the support address your username.

**Comment by ScottPeterJohnson** [comment]
Apparently Roundcube keys its user settings by the mail hostname, not just the username, so when I changed the internal DNS record Roundcube pointed to it stopped using all the old rows on new logouts. I reverted back to the settings from a week ago; try logging out and back in and see if your identities returned.

**Comment by bai-yi-bai** [comment]
Hi, thanks for finding the root cause... I checked to see if my old identities were back... unfortunately they are not.

**Comment by ScottPeterJohnson** [comment]
Are you sure you logged out of Roundcube? (The red Logout button).
They won't show up unless you log out/back in. They do seem to be there in the DB.

**Comment by bai-yi-bai** [comment]
Finally! Two logouts/closed my browser and they re-appeared.
Thanks!
