### ISSUE TITLE
Roundcube contacts address book Default empty, error with CardDAV sync

### ISSUE THREAD

**Issue by rnkn** [ScottPeterJohnson/purelymail-issues#157]
Hello,

I think I was trying to import a VCF file when I started receiving the following error in Roundcube:

> Sync of CardDAV addressbook Default failed: Expected Multistatus HTTP request was not successful (401 Unauthorized)

I then tried **Settings > Preferences > CardDAV > Delete locally cached data for this addressbook (next resync starts from scratch)** and now my Default address book is empty in RoundCube and each sync results in the error above.

I still have contacts on iOS devices, which appear to sync to the CardDAV server, so I think this is isolated to Roundcube.

**Comment by ScottPeterJohnson** [comment]
Can you DM (or email or whatever other private means) me the affected user name?
