### ISSUE TITLE
Sent emails are not in sent folder!

### ISSUE THREAD

**Issue by 5y4m** [ScottPeterJohnson/purelymail-issues#160]
Today, I replied to an email from K-9 mail and found it is not in sent folder. I checked in the webmail too. It was not there either.

To test, I emailed to an external email account from webmail. It reached there, but it was still not in sent folder.

**Comment by ScottPeterJohnson** [comment]
I would first check your settings- adding mail to a folder after sending it is actually completely a clientside thing. In K9mail it's an "Upload sent messages" account checkbox, and you also want to make sure under Folders that the "Sent folder" is identified as "Sent". For webmail it should be correctly set up by default, but you could check it also identifies your sent folder as "Sent".

**Comment by 5y4m** [comment]
Sent folder was set as “_Automatic_ (None)” just like other folders (Archive, Draft, Trash, Spam etc.). Anyway, I changed it to 'Sent'. 

Now I tested from K-9mail and webmail. It worked correctly. Emails landed on Sent folder.
