### ISSUE TITLE
"Not Junk" is not working

### ISSUE THREAD

**Issue by alexandergeiler** [ScottPeterJohnson/purelymail-issues#163]
Hi,

I get emails from my phone system when I miss a call or someone has left a message on my answering machine.
The phone system is integrated in my router from the company Fritzbox (very well known in Germany).
The Fritzbox uses a foreign email provider (web.de) to send me messages.

Purleymail has been recognizing these emails as SPAM for weeks.

Email header of an affected email:
[Fritzbox/router use web.de to sent the message via google to purelymail]
(few details I have removed)

X-Spam-Status: No, score=1.97 required=5 tests=BAYES_00,DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,FREEMAIL_FORGED_FROMDOMAIN,FREEMAIL_FROM,FROM_EXCESS_BASE64,HEADER_FROM_DIFFERENT_DOMAINS,HTML_MESSAGE,RCVD_IN_MSPIKE_H3,RCVD_IN_MSPIKE_WL,RCVD_IN_ZEN_BLOCKED_OPENDNS,SPF_HELO_NONE,SPF_PASS,URIBL_DBL_BLOCKED_OPENDNS,URIBL_ZEN_BLOCKED_OPENDNS,WEIRD_PORT,PURELYMAIL_IP_REPUTATION autolearn=no autolearn_force=no version=3.4.6
X-Pm-Spam-PURELYMAIL-IP-REPUTATION: 1.97;EffectiveIp=91.89.234.92,SpamProbability=0.4
Return-Path: <alXXXXder+caf_=alXXXXder=agXXXXXX.de@geiler-XXXX.de>
Delivered-To: alXXXXder@ageiler.de
X-Pm-Original-To: alXXXXder@ageiler.de
Authentication-Results: purelymail.com; spf=pass (domain of geiler-XXXX.de designates 209.85.215.170 as permitted sender) smtp.mailfrom=geiler-XXXX.de; dkim=pass header.i=web.de; dmarc=pass (p=none) header.from=thebXXXXXXski@web.de
Received: from mail-pg1-f170.google.com (EHLO mail-pg1-f170.google.com) ([209.85.215.170])
    by smtp.purelymail.com (Purelymail SMTP) with ESMTPS id -913047134
    for <alXXXXder@ageiler.de>
    (version=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384);
    Sun, 16 Apr 2023 13:08:49 +0000 (UTC)
Received: by mail-pg1-f170.google.com with SMTP id 185so1782212pgc.10
    for <alXXXXder@ageiler.de>; Sun, 16 Apr 2023 06:08:49 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
    d=1e100.net; s=20221208; t=1681650528; x=1684242528;
    h=ui-outboundreport:mime-version:subject:date:to:from:message-id
    :dkim-signature:delivered-to:x-gm-message-state:from:to:cc:subject
    :date:message-id:reply-to;
    bh=jp3dmudY8TX3fxU0bVV9FQ/m5aTU56bgj2YuyY0cwX4=;
    b=Da+EzX6p8g7FuCLm8I5TOy7X9TVD831RxB83uOGf03VN1Bh2U9ixsHIk93p1rTfRNy
    0oGD9HdOfYlgiEDtxYB09OcPNpGO9UvDuABZTNuPWtSX649pPZORNGri8+zB7flFCWVM
    B5m4l35YXwX/tlZHGoAiyilZ7c1hj59MDNucy4Sh736dVbY6TTnlvey4lid15DLzmFVS
    WxBwa/iDiGYxncrtSJtYM/+bfhguWnfDZTWcmBp//gB93EAtxPfOTEJ3sAhURASaIju/
    pbYVjrb/5zk+McohksgvOTM3T1mtSspHI+x4NuJvPvvKUoYjUfBBwyjTF+pEHJ6JXBs4
    EtuQ==
X-Gm-Message-State: AAQBX9cIFsXjubfng4Pf9ITOOA4RqekKyfm4RU3CTJhqvfbrLnkZMaxz
    du8QHzoFbIAmeLThzyEMJsqv9SN+/x/VSKgKTLKrP/QZKsTdqXjykiJftkIArA==
X-Received: by 2002:a63:2683:0:b0:513:b7a5:cb27 with SMTP id m125-20020a632683000000b00513b7a5cb27mr2243122pgm.0.1681650528015;
    Sun, 16 Apr 2023 06:08:48 -0700 (PDT)
X-Forwarded-To: alXXXXder@ageiler.de
X-Forwarded-For: alXXXXder@geiler-XXXX.de alXXXXder@ageiler.de
Delivered-To: alXXXXder@geiler-XXXX.de
Received: by 2002:a05:6a10:95a7:b0:48f:8541:7bbf with SMTP id w7csp1592264pxn;
    Sun, 16 Apr 2023 06:08:46 -0700 (PDT)
X-Google-Smtp-Source: AKy350YP0w+GH8m57Jer/bk42gW6kv1ao2TTqMKzWque59NIe+8Ijp/l31o7sitZK2jFNX6dlu+f
X-Received: by 2002:a7b:ce14:0:b0:3f1:65de:764 with SMTP id m20-20020a7bce14000000b003f165de0764mr3832646wmc.32.1681650526667;
    Sun, 16 Apr 2023 06:08:46 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1681650526; cv=none;
    d=google.com; s=arc-20160816;
    b=R0UqwonBD0fSSX2Zr3RdIScNIXACciTZ9rweUSe/TgMICC0xkJoK/XYvtbynBvA/7E
    zLGqM16Rvs5VRpomHNiMmuYuCWagMZakHJ39Bj5iBb2DA7ddKMGhyxytzy8MORi57lDf
    UEN64MT06d030dmr+xuSafGun1Ty5E13AlOGN4rvVVcrF/VJS+NaR/5roJyoELvVgBT7
    mOP2h+zpCH0MGQbD/cySI08zU2+EfaHsCG0UAzejb+BMRT+EU8ZTLZZrTyetueDY58MI
    yeO9YdlUwDO5VqvHwH2pdwIWCgNAcx2E1iW5dp3T67Rjmzzd1qoJlRrUVMWpDT4OnX8D
    y8qA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
    h=ui-outboundreport:mime-version:subject:date:to:from:message-id
    :dkim-signature;
    bh=jp3dmudY8TX3fxU0bVV9FQ/m5aTU56bgj2YuyY0cwX4=;
    b=HnBkrh5n2G5fvu2DZdQR6VSyJQzmIAebp2zTahkqaOnvmxD/FxvmeG1njF28wwKePR
    p1k6UNNW2TTnnxZcnH4R4PvTJd96QraDWN6VUBx8IdjIrBW/44kBbwQmH6MVdJlax/nn
    a7ZIztABA11N32ba4f8cv57r0O1gqFBXlTu9s+Bw5MjmthB89lGGSjUnGPXWR6UvaXTV
    h8TU+ffzeptPlJv1CDbzsGTbPePBuVoF6yL5aCCzDoIXve7TCaJ8upM/Lj4ktJuCbb90
    sJ2xal4XtZt4lcSHLtrEWsEDezPemC7AriMyaotnL0BldxBKjHrxecB7ucvex5a0XGnI
    3cvg==
ARC-Authentication-Results: i=1; mx.google.com;
    dkim=pass header.i=@web.de header.s=s29768273 header.b="D/GdxFZB";
    spf=pass (google.com: domain of thebXXXXXXski@web.de designates 212.227.17.12 as permitted sender) smtp.mailfrom=thebXXXXXXski@web.de;
    dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=web.de
Received: from mout.web.de (mout.web.de. [212.227.17.12])
    by mx.google.com with ESMTPS id c16-20020a7bc010000000b003f07ddfd8dcsi8767645wmb.193.2023.04.16.06.08.46
    (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
    Sun, 16 Apr 2023 06:08:46 -0700 (PDT)
Received-SPF: pass (google.com: domain of thebXXXXXXski@web.de designates 212.227.17.12 as permitted sender) client-ip=212.227.17.12;
Authentication-Results: mx.google.com;
    dkim=pass header.i=@web.de header.s=s29768273 header.b="D/GdxFZB";
    spf=pass (google.com: domain of thebXXXXXXski@web.de designates 212.227.17.12 as permitted sender) smtp.mailfrom=thebXXXXXXski@web.de;
    dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=web.de
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=web.de; s=s29768273;
    t=1681650526; i=thebXXXXXXski@web.de;
    bh=jp3dmudY8TX3fxU0bVV9FQ/m5aTU56bgj2YuyY0cwX4=;
    h=X-UI-Sender-Class:From:To:Date:Subject;
    b=D/GdxFZBTNlOEf1i8cUtWNxeB8zUUlHRx4OjrV8kDa6ZeomxB4aLfKjxlxsFuUfYC
    5wVXSSCI2L2t2lFEnoQIpRhpyxQNUVKejofKjcKgJFSoKqLrnDrTcZLhJCI+uXsbXA
    MkiL85UGiuHG/SXnJpqAp03WIWUJRKpSI8cjn5al7g/IsNl6DzX5+t7bRgA37QRkWG
    maEqB4IgXoOdEOw+P/GSWt91+VSjlHRkrI225sVm9AyMlwqQTPNRVlK5a6LVEeg9K/
    OnQW6GTtbZ3FHrlAVvgcDXmEp6xeUXaD2GC4GKj45vDN26WNbornTEMBfVO19EE06c
    qVy6gqavKXGqg==
X-UI-Sender-Class: 814a7b36-bfc1-4dae-8640-3722d8ec6cd6
Received: from fritzbox ([91.89.234.92]) by smtp.web.de (mrweb105
    [213.165.67.124]) with ESMTPSA (Nemesis) id 1MBjIE-1pe7293khY-00CUod; Sun, 16
    Apr 2023 15:08:45 +0200
Message-Id: <1129385.mmailer1895512009@fritz.box>
From: "=?UTF-8?B?RlJJVFohQm94IDY0OTAgQWxleGFuZGVy?=" <thebXXXXXXski@web.de>
To: <alXXXXder@geiler-XXXX.de>,
    <aXXXXXXXXXXXXXXXXXXde>
Date: Sun, 16 Apr 2023 15:08:45 +0200
Subject: =?UTF-8?B?QW5ydWYgdm9uIFN5bHZpYSAmIFRvcnN0ZW4gKDA2MjA1MjU1MzUwOCk=?=
Mime-Version: 1.0
Content-Type: multipart/alternative;
    boundary="==AVM_Fritz_Box==multipart/alternative==1=="
X-Provags-ID: V03:K1:eSal4+TITZLmU+u7roV4TlUBWJdaxGVR1cBuxfx+jCcOAwWSkA1
    eUoncWz8D0gNZZSnWSi3azDix8QkM3PvmiXZ8b1DGvM1UDFMvQRmtKMOhMmf5B2al/+Msao
    dR89d75PxCGHs1yoN0lwnDBH7yGy1r/p8MTFRU9MOM7cXFh3B7MvWMt2xX7B6g0J67gHRQG
    eDgShBLj3CtNerFvh6WPg==
X-Spam-Flag: NO
UI-OutboundReport: notjunk:1;M01:P0:ZCbcsXqaB8o=;TVY43ZD93+7MA7gvrhZZFuxeOI+
    F/qBhahEp/YUkAKrND6onX8oyKz0Utr86y6BiiiRFn4AWSe0MgHRDQkHPdN6ZT4Dno4yYN4z7
    1cVqEzN2x7oilye/ZVRbiBTsU5e31BVw9IuQEt4E0GP+srxcHxGTq2yvXddSDl3V6LnTGMl9g
    ZbmGOxPOSui8IFf8VmM01ysfr31v4E1CjYKYDI+1CqdKyBmy/FKsO/52IHewiRU3NihLa874R
    aTRRq6ZBN9GtQPhw7xk50UWNJFnp6UVeLBiEsPv+ejEKTOoKHENUqHC8tr2xzVz2mGE2T7MAT
    LmILvvamjXqrkhqFpoSCGSyuNSq1Smo8g/PMPNyqJXsj+sqlH/1/eULQdiRqtiY0DJRIWNjpL
    VzdcxnPnjnH9rZA3SKnAFUhDBbaFGNMCrNGZGVlBv3sWsOPzCJFGrv01zera5yccWhrFcrq2J
    PUJ5XzlfbJJQYqu2HzI2AugPUxdZn0oF8YCqhC5qCgH/moa7EyqP3hVJw+eCpKrdq3/4EaKXC
    U5rZjCClR0cepgdX0CChGHZDz3HP8iJJ696WgnEVMevBKwaijqc87KS1u0FWNnjkMIw0/bBha
    c5dw9TPQeZWRUBSWug2ax3V0x1VFLFoBNGOuSKQCLLERoiC7tkFbZ/bcBggB0JW48Bugq3Pdb
    QWCMfKz3q9k9LN3M2n6kKpE4MCipWkUqjKFMP+VpPhlLYUoVWxkvCQSnE09Jdj5l/4/uXBA+H
    yi7dQvm7AdqQDsglw9bblO1V9bvFhoUIJrzL+gR6By3mXax4dH9KUB8jMaJBNSmCW/H5S1nL7
    SNb3KE/1hIioNK9FdygwXMkPmgy5V2R6E6UTqv/1ef3z4TdD/qAbhnjtSk/71yhnwsV+5v+ge
    8tZcdVx3nNPXko5wLL+vStO7qMA1IOExIqKqxkYpzeR+zO+V4KAu6Cxh4mjAOfbdj/hNKvjjO
    BmDxBM4Nb14ZAANatc/O8vT4Xgg=

I found the email in my SPAM folder and I can click "not junk".
![not_junk](https://user-images.githubusercontent.com/4689177/232466959-adc1ccdf-b327-428f-b0d7-7263b9b4bdf8.png)

I will find that email for few seconds in my inbox.
![not_junk2](https://user-images.githubusercontent.com/4689177/232466989-783c4818-e024-40ef-8ef1-e4cf68ff2e5f.png)

the email is moved back to the SPAM folder after a few seconds.
![not_junk4](https://user-images.githubusercontent.com/4689177/232468086-375a6e9d-1fb8-43a3-a3d7-41acf13de821.png)

I am not able to explain purelymal that is is ***not junk***.

**Comment by alexandergeiler** [comment]
Any news in this topic?
Anyone else have an issue with the "not junk" function?

**Comment by ScottPeterJohnson** [comment]
I haven't ever seen this happen myself, but I do note the following:

> X-Spam-Status: No, score=1.97 required=5 

As far as I can tell, Purelymail did not classify your message as Junk. And there's nothing that will drag your mail back to the junk folder after you move it to the inbox. Are you sure you don't have any third party client hooked up to that account that's junking your mails?

**Comment by alexandergeiler** [comment]
Thank you for your hint.
I found the issue.
The mailaddress where on the blocklist of my smartphone app Fairmail and was moved afterwards to SPAM again.

**Comment by alexandergeiler** [comment]
Thank you for your hint.
I found the issue.
The mailaddress where on the blocklist of my smartphone app Fairmail and was moved afterwards to SPAM again.
