### ISSUE TITLE
Billing reminder

### ISSUE THREAD

**Issue by EvilOliverlord** [ScottPeterJohnson/purelymail-issues#166]
Didn't get any kind of billing reminder or low funding notice. My e-mail simply stopped working. It took me a long time to figure out why, to notice the yellow 'low credit' ribbon on the PurelyMail site, then to remember where to go to pay. So far as I can tell, I had auto-pay set up. Maybe it's because I used a PurelyMail address as my admin address (to which notices were then not delivered?). In any case, this seems like a bug. I was happy to pay the amount, but spent a long time before realizing that was what was wrong.

**Comment by ScottPeterJohnson** [comment]
You should have received a reminder and a notice at your "billing address" (which is by default your admin address). If you can PM/email me your address somehow I can look at what happened to it.

**Comment by ScottPeterJohnson** [comment]
Closed (user did find message).
