### ISSUE TITLE
Feature Request - API operation for listing users

### ISSUE THREAD

**Issue by cramey** [ScottPeterJohnson/purelymail-issues#172]
The API supports listing routing rules and domains, but not listing users, even though it can be used to both create and delete users.

**Comment by richard-scarrott-springer** [comment]
I would also like to request this. 
We have an org use case for this and no obvious workaround,

**Comment by ScottPeterJohnson** [comment]
See https://news.purelymail.com/api/index.html#/User/List%20Users

**Comment by richard-scarrott-springer** [comment]
I appreciate the quick response, but has this actually been put live?

**listUser** works beautifully now but isn't in the live Swagger documentation
