### ISSUE TITLE
Underscores (_) Not Allowed in Routing?

### ISSUE THREAD

**Issue by bai-yi-bai** [ScottPeterJohnson/purelymail-issues#174]
Hello,

Today, I tried setting up some routing addresses with underscores (_) using the exact address option. I tried setting up two routing addresses and sent from two other emails accounts and they did not arrive in my inbox. For one of them I set up a sieve rule, but the other I didn't set up anything.

I assume there is a problem with emails containing underscores... but I wonder if there are other characters which are impacted.

Thanks in advance for looking into this; it's not major for me.

**edit**
Follow-up, I got a bounce back email "(Rerouted): User isn't located here (5.1.1)."
The other email I used with underscores was for a system I don't have control of, so I don't know if it bounced back.

**Comment by ScottPeterJohnson** [comment]
I can't be sure without knowing your exact setup, but I'm betting what you're seeing is an interaction with symbolic-subaddressing, a routing option that's probably enabled for the domain you're trying to route. By default, it will ignore everything after the underscore (and other special characters), and then try to route just what's left- which won't match your routing rule with an underscore in it.
