### ISSUE TITLE
Deleting all emails from search gives error

### ISSUE THREAD

**Issue by adityajpatil** [ScottPeterJohnson/purelymail-issues#175]
In the webmail, if I search for a query, select all the emails and try to delete them, I get an error.

Repro steps:
1. In webmail, search for some query
2. Go to select > All at the top
3. Right click on any of the search result(or in the general results area) and select delete
4. Get this popup error: _Server Error: Failed to send SELECT command_
5. Also get this popup: _Search returned no matches_
6. None of the email are deleted

However, if I instead try to archive them, that works fine.

**Comment by ScottPeterJohnson** [comment]
I fixed this a couple weeks ago; it was some obscure PHP bug with the way Purelymail does partial searches in its webmail. The Archive button of course had a completely different implementation than Delete, despite both being essentially "move to folder".
