### ISSUE TITLE
IPv6 missing from SPF record

### ISSUE THREAD

**Issue by 9ary** [ScottPeterJohnson/purelymail-issues#178]
Hi,

I've noticed that my outgoing emails are soft-failing SPF because they are sent over IPv6, but the SPF record doesn't list any ipv6 addresses:
```
_spf.purelymail.com.	3600	IN	TXT	"v=spf1 ip4:34.202.193.197 ip4:54.89.13.140 ip4:3.231.132.23 ~all"
```

Additionally, I see that PM's SPF record ends with `~all`, which seems to negate/get in the way of my own configuration of `-all` (SPF is soft-failing rather than hard-failing).

This is my SPF record:
```
.	300	IN	TXT	"v=spf1 include:_spf.purelymail.com -all"
```

**Comment by ScottPeterJohnson** [comment]
Are you sure this is mail sent through us? We don't use IPv6 for sending...

**Comment by 9ary** [comment]
Yes, I sent it through the hosted roundcube.
I just checked again, the address that shows up on the recipient's side is 2600:1901:101::11, ~~I do believe this belongs to cloudflare, which makes sense because they are using their mail forwarding service, so that may just be it.~~ This is a google cloud address according to geoip, so I guess gmail is to blame.

Further testing shows that the recipient is also seeing a google address as the sender when receiving on a wildcard inbox (different domain managed by google workspace), but SPF passes properly when receiving on a valid address on the same domain.

Either way, it seems the problem is not on your end, sorry for the false positive.
