### ISSUE TITLE
Changing identity breaks webmail.

### ISSUE THREAD

**Issue by lukehmcc** [ScottPeterJohnson/purelymail-issues#180]
If you create an email inbox, port in emails, then change the email identity, this change isn't reflected in the webmail inbox. It will keep trying to send emails from the old email which clearly won't work.

This issue is reproduceable for me.

**Comment by ScottPeterJohnson** [comment]
Seems like Roundcube denormalizes the email address into the default identity field, and that doesn't get updated when Purelymail changes the username (the actual username row does). Should be a simple fix.

**Comment by ScottPeterJohnson** [comment]
I added a fix (although it's a little hacky since it assumes any identity email-from for the changed email should also change and that might not necessarily be the case).
