### ISSUE TITLE
UI uglifcation when adding Action row to Sieve Filter

### ISSUE THREAD

**Issue by rnkn** [ScottPeterJohnson/purelymail-issues#181]
## Description

I first reported this upstream at https://github.com/roundcube/roundcubemail/issues/9139 however this appears to be server specific.

There is a UI misalignment/corruption/uglification when adding a new Action row to a Sieve Filter in the Elastic skin. The initial dropdown should display the “Move message to” option but is blank, while the second dropdown is styled in the browser default style not the skin, and the add & delete buttons are misaligned. See attachment:

![IMG_0227](https://github.com/roundcube/roundcubemail/assets/1256849/254798ed-fb64-4a95-96d0-894e78591df5)

## To reproduce:

1. Navigate to Sieve Filters
2. Select an existing Filter or Create new
3. Select “+” on Actions row

## Expected results:

Row is added with consistent style.

## Actual results:

See above attachment.

**Comment by ScottPeterJohnson** [comment]
It seems like Roundcube bugs out if the relational and spamtest extensions aren't supported. Since those are useful extensions I'll add them, though technically the bug is Roundcube's.

**Comment by ScottPeterJohnson** [comment]
Seems to be fixed now.
