### ISSUE TITLE
SMTP smuggling

### ISSUE THREAD

**Issue by rEnr3n** [ScottPeterJohnson/purelymail-issues#192]
https://sec-consult.com/blog/detail/smtp-smuggling-spoofing-e-mails-worldwide/

I haven't seen any news from you regarding this. What's the status of your server regarding this?

**Comment by ScottPeterJohnson** [comment]
Fairly certain it's inapplicable. There's no difference in interpretation between outbound/inbound line parsing in the underlying SMTP software, and also outbound never talks to inbound over SMTP.
