### ISSUE TITLE
Routing issue: Subdomain affecting root domain

### ISSUE THREAD

**Issue by voodoologic** [ScottPeterJohnson/purelymail-issues#197]
i'm trying to have two catchall accounts, one at passiveobserver.com and one at d.passiveobserver.com, they both cannot work at the same time.

I have two domains setup in PM: d.passiveobserver.com and passiveobserver.com.  If I set a catchall in one of them, it will refuse to honor the catchall in the other.   For instance, if I set d.passiveobserver.com to go to doug@dougheadley.com, a registered account name in PM, then my catchall at the root domain (passiveobserver.com) doesn't work.  The same behavior happens when I switch the rules so that I define the catchall for root domain, the result it that the the "d" subdomain's catchall fails.

**Comment by voodoologic** [comment]
I figured out a work around.  If I set both rules at the same time, it works as expected.

![Screenshot 2024-01-12 at 1 16 34 PM](https://github.com/ScottPeterJohnson/purelymail-issues/assets/190596/916dc5a6-b4b5-494f-a141-27bead275f69)

You have to click "Add New" to get a new rule.  Then you set the root domain and the subdomain at the same time by entering the desired rules and hitting send.   It's working right now so fingers crossed.

**Comment by ScottPeterJohnson** [comment]
Basically the reason for this is that there's no concept of "subdomains" in Purelymail; they're treated as two separate domains.
