### ISSUE TITLE
Custom DMARC record not accepted

### ISSUE THREAD

**Issue by Sharparam** [ScottPeterJohnson/purelymail-issues#200]
I use the Cloudflare feature for processing DMARC reports, and would like to keep using that while also using Purelymail for my domain(s), and so instead of using the CNAME `_dmarc` method, I have my own `_dmarc` TXT record as such:

```
$ drill _dmarc.hellberg.family txt
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 16597
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; _dmarc.hellberg.family.	IN	TXT

;; ANSWER SECTION:
_dmarc.hellberg.family.	300	IN	TXT	"v=DMARC1;  p=reject; rua=mailto:<cf-generated-id>@dmarc-reports.cloudflare.net,mailto:dmarc@purelymail.com; ruf=mailto:dmarc@purelymail.com; fo=0:1:d:s;"

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 37 msec
;; SERVER: 192.168.1.1
;; WHEN: Fri Jan 26 12:02:52 2024
;; MSG SIZE  rcvd: 220
```

But with this, Purelymail reports DMARC as "not configured" on the domain status:

![image](https://github.com/ScottPeterJohnson/purelymail-issues/assets/551094/a745115a-98c0-4f65-b33c-1cb15f3d2d58)

Is this simply a display issue, and the DMARC features will keep working (since it's still configured to send report emails to Purelymail)?

**Comment by ScottPeterJohnson** [comment]
This is a display issue (sort of, it's halfway intentional it tells you it's not configured for Purelymail but it should have its own error messages).
DMARC should keep working just fine.

**Comment by Sharparam** [comment]
Thanks for the clarification! Perhaps it should check if Purelymail's DMARC email is part of the `rua` and `ruf` properties when DMARC isn't using a CNAME record (or just a bit of text saying it will still work as long as you include the emails).
