### ISSUE TITLE
CORS for API

### ISSUE THREAD

**Issue by icepcp** [ScottPeterJohnson/purelymail-issues#242]
Hello, excuse my lack of knowledge, but may I ask if the purelymail api has cors requirement? Running the API specs with my key shows that there is a CORS error (https://news.purelymail.com/api/index.html) and running it in my API client it doesn't work until I enabled CORS bypassing, I'm not too sure if this is an issue on my side of if it is the API's side

Thanks in advance

**Comment by ScottPeterJohnson** [comment]
The CORS issue is probably from your browser. It might just not be possible to do things like restfox/our API's try it out anymore without running into CORS issues. I think at some point browsers began requiring specific CORS opt-ins for sending cross origin requests, which the API obviously won't do. (I mean I guess it could, but that's a security issue given browsers and probably not worth doing for just web testers.)

I guess probably I need to fix the docs at some point however.
