### ISSUE TITLE
Account Ownership verification TXT with Godaddy

### ISSUE THREAD

**Issue by SASS114019** [ScottPeterJohnson/purelymail-issues#249]
Instructions say to leave Value blank.  Godaddy won't take it that way they want an @ in that spot at least, so I cannot add the domain.  All other records verify, just not the TXT

Solution would be to allow @ as well as blank space maybe?

**Comment by ScottPeterJohnson** [comment]
The instructions on the Add Domain page are for a variety of registrars. It's not that _we_ require you to use blank or an @ in particular to denote the root domain; that's how your particular DNS provider does it. I think the instructions do say to use either blank or @, whichever works.

**Comment by SASS114019** [comment]
I put a @ there and now it all works.

Godaddy would not take the record with the field blank.  I got the 
impression your system was specifically looking for a TXT record with 
that field empty.  Someone (possibly you) changed something on your end 
and now it works with a @ in there - even though that character 
functionally means nothing in a TXT record (as far as I know)

On 2024-10-10 10:00, Scott Johnson wrote:

> The instructions on the Add Domain page are for a variety of 
> registrars. It's not that _we_ require you to use blank or an @ in 
> particular to denote the root domain; that's how your particular DNS 
> provider does it. I think the instructions do say to use either blank 
> or @, whichever works.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/ScottPeterJohnson/purelymail-issues/issues/249#issuecomment-2404642807
[2]
