### ISSUE TITLE
CalDAV and Thunderbird Lightning synchronisation

### ISSUE THREAD

**Issue by RamblingRoss** [ScottPeterJohnson/purelymail-issues#250]
Up until today Thunderbird 128.3.1 (64-bit) on Windows 11 (23H2) has been happily synchronising with and displaying CalDAV source exposed at https://purelymail.com/webdav/XXXX/caldav/default/

As of this morning the Thunderbird Lightning calendar is empty.

The same feed accessed on Android using DAVx5 appears to be working correctly.

From the Thunderbird log files it appears that a 400 Bad Request is being sent back form the PurelyMail servers. Any recent software changes that could be causing this?

[log.txt](https://github.com/user-attachments/files/17384458/log.txt)

**Comment by ScottPeterJohnson** [comment]
Thunderbird specifically is trying to use our recently released webdav-sync report to more efficiently sync CalDAV, but a minor error on their half (they set a Depth: header to 1 when it should always be 0) means Purelymail is throwing an error when it tries. 
I'm going to fix this by simply not throwing the error and not checking the header.

**Comment by RamblingRoss** [comment]
All appears to be working now. Thanks for the speedy resolution!
