### ISSUE TITLE
You don't know whether my phone number can receive SMS

### ISSUE THREAD

**Issue by ScottPeterJohnson** [ScottPeterJohnson/purelymail-issues#76]
(This issue was imported from Gitea)
**df** on July 24, 2021:
The Trial signup needs a phone number that can receive SMS, and for UK it seems to think that means a mobile number.

However a personal number (that can't receive texts) +44 7092 nnnnnn is accepted while my landline (that can) +44 20 nnnn nnnn is excluded.

That's probably being a bit too clever.

**Comment by ScottPeterJohnson** [comment]
Comment by **Scott** on July 29, 2021:
Sorry for the late response- I just got back from vacation.

I was using Google's libphonenumber to verify the type of the phone number could include text; but since that seems to be inaccurate in at least your case I've updated it to accept any valid phone number instead. Let me know if your number works now.

**Comment by ScottPeterJohnson** [comment]
Comment by **Scott** on August 11, 2021:
Assuming this is fixed, feel free to reopen if you experience further issues.

**Comment by DoozyDoz** [comment]
I experience this issue too, my contact is +256 7563....
