### ISSUE TITLE
No sent messages in Sent folder

### ISSUE THREAD

**Issue by ScottPeterJohnson** [ScottPeterJohnson/purelymail-issues#95]
(This issue was imported from Gitea)
**gschuck** on February 25, 2022:
I thought it was something with Outlook but it doesn't show anything in the Sent folder in the Purelymail Webmail browser either. I looked for a setting but couldn't find one. What am I missing?

**Comment by ScottPeterJohnson** [comment]
Comment by **Scott** on February 25, 2022:
So the way that IMAP/SMTP works is that your *client* adds messages it sends to the Sent folder, not the *server*. I'm not super familiar with Outlook, but it looks like they should have a setting for this:
https://docs.microsoft.com/en-us/outlook/troubleshoot/email-management/email-sent-are-not-saved-to-sent-items-folder

**Comment by ScottPeterJohnson** [comment]
Comment by **Scott** on March 11, 2022:
Closed (inactive, possibly answered).

**Comment by garritfra** [comment]
Hi, I just noticed the same problem. That the client is in charge of placing the mail in the "sent" folder makes sense, but why does this not work in webmail either? Tried k6 too, without avail.

Thanks!

**Comment by ScottPeterJohnson** [comment]
@garritfra Not sure- are you looking at/subscribed to the right folder (name is "Sent")? Does it not seem to add a message when sent from K-9/webmail? Feel free to open a new issue if you can't figure it out.
