### ISSUE TITLE
Bug - Impossible to unselect the phone reset checkbox

### ISSUE THREAD

**Issue by ScottPeterJohnson** [ScottPeterJohnson/purelymail-issues#97]
(This issue was imported from Gitea)
**lbouriez** on March 11, 2022:
Hello, already mentionned on Discord

In the users settings, I have this message: Note that phone-based password reset weakens 2FA

When I uncheck the `Allow 2FA Reset on the phone line`
Then I click on Save
I am redirected to the Account page with this message: `User updated!`

BUT when I go back, the message still there and the checkbox checked.

**Comment by ScottPeterJohnson** [comment]
Comment by **Scott** on March 13, 2022:
This doesn't seem to be a bug that normally happens. Can you tell me what browser you're using?

**Comment by ScottPeterJohnson** [comment]
Comment by **lbouriez** on March 13, 2022:
Microsoft Edge on both mobile and laptop (based on Chromium)

**Comment by ScottPeterJohnson** [comment]
Comment by **lbouriez** on March 13, 2022:
I tried in private navigation, same results.

**Comment by ScottPeterJohnson** [comment]
Comment by **lbouriez** on March 13, 2022:
I removed my real information but there is the page:
![image](/attachments/692507e0-4091-42dc-ac78-490bb96478ac)
I uncheck the checkbox, save and get here:
![image](/attachments/8f7f5329-681a-4c01-bb51-ef15ea6603f8)
Then when I go in the user settings, checkbox is checked, warning is here

**Comment by ScottPeterJohnson** [comment]
Comment by **Scott** on March 14, 2022:
This odd issue seems like it only affected non-US phone numbers and should now be fixed.

**Comment by floppyman** [comment]
Sorry for commenting a closed issue.

However I just signed up for a trial account, and I have the exact same issue, when unchecking the checkbox for phone number and saving, the check is back when opening the user edit page.

I have a phone number from Denmark.
